import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here

        List<String> ids = new ArrayList<>();
        List<Integer> count = new ArrayList<>();
        List<SalesPromotion> ALL_SALES_PROMOTIONS = salesPromotionRepository.findAll();
        List<Item> ALL_ITEMS = itemRepository.findAll();
        String order = "";

        for (String s : inputs) {
            ids.add(s.substring(0, 8));
            count.add(Integer.parseInt(s.substring(11)));
        }

        int price = 0;
        int sum = 0;
        int afterPromotion = 0;

        //计算总价格
        for (int i = 0; i < ids.size(); i++) {
            for (Item item : ALL_ITEMS) {
                if (item.getId().equals(ids.get(i))) {
                    price = (int) item.getPrice() * count.get(i);
                    sum = sum + price;
                    order += item.getName() + " x " + count.get(i) + " = " + price + " yuan\n";
                }
            }
        }

        // 若总价未超过30块
        if (sum <= 30) {
            afterPromotion = sum;
            return "============= Order details =============\n" +
                    order +
                    "-----------------------------------\n" +
                    "Total: " + afterPromotion + " yuan\n" +
                    "===================================";

        }

        //若总价超过30元，则使用优惠
        else {
            //第一种优惠，30-6
            int PromotionOne = sum - 6;
            String displayOne = "满30减6 yuan，saving 6 yuan\n";

            //第二种优惠，某些菜半价
            //存储使用促销2后的总价
            int PromotionTwo = sum;
            List<String> promotionList = new ArrayList<>(); //存储减价后的菜品信息
            String displayTwo = ALL_SALES_PROMOTIONS.get(1).getDisplayName();
            int saveMoney = 0; //节省金额

            for (int i = 0; i < ids.size(); i++) {
                for (SalesPromotion salesPromotion : ALL_SALES_PROMOTIONS) {
                    for (String id : salesPromotion.getRelatedItems()) {
                        if (id.equals(ids.get(i))) {
                            for (Item item : ALL_ITEMS) {
                                if (item.getId().equals(id)) {
                                    promotionList.add(item.getName());
                                    saveMoney += item.getPrice()/2;
                                    PromotionTwo -= item.getPrice() /2;
                                }
                            }
                        }
                    }
                }
            }

            String promotionName = String.join("，", promotionList);
            displayTwo += " (" + promotionName + ")，";
            displayTwo += "saving " + saveMoney + " yuan\n";

            //判断哪个优惠更合适
            if (PromotionOne <= PromotionTwo) {
                afterPromotion = PromotionOne;
                return "============= Order details =============\n" +
                        order +
                        "-----------------------------------\n" +
                        "Promotion used:\n" +
                        displayOne +
                        "-----------------------------------\n" +
                        "Total: " + afterPromotion + " yuan\n" +
                        "===================================";
            } else {
                afterPromotion = PromotionTwo;
                return "============= Order details =============\n" +
                        order+
                        "-----------------------------------\n" +
                        "Promotion used:\n" +
                        displayTwo +
                        "-----------------------------------\n" +
                        "Total: " + afterPromotion + " yuan\n" +
                        "===================================";

            }

        }
    }
}




